# Generated by Django 5.1.4 on 2025-01-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=75),
        ),
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
