"""empty message

Revision ID: 6de84f34b5de
Revises: 0770f38a9c5d
Create Date: 2025-02-10 16:39:49.129187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de84f34b5de'
down_revision: Union[str, None] = '0770f38a9c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'event_registrations', 'profiles', ['profile_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'event_registrations', 'events', ['event_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'events', 'locations', ['location_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'events', 'users', ['author_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'events', 'categories', ['category_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'events', 'organizers', ['organizer_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'organizers', 'users', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_constraint(None, 'organizers', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    # ### end Alembic commands ###
