"""empty message

Revision ID: aa6a92e73b21
Revises: 40ccc74ca631
Create Date: 2025-02-18 12:14:51.445499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa6a92e73b21"
down_revision: Union[str, None] = "40ccc74ca631"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_event_organizers_organizer_id_organizers"),
        "event_organizers",
        "organizers",
        ["organizer_id"],
        ["[[[[id]]]]"],
        ondelete="CASCADE",
        use_alter=True,
    )
    op.create_foreign_key(
        op.f("fk_event_organizers_event_id_events"),
        "event_organizers",
        "events",
        ["event_id"],
        ["[[[[id]]]]"],
        ondelete="CASCADE",
        use_alter=True,
    )
    op.create_foreign_key(
        op.f("fk_event_registrations_event_id_events"),
        "event_registrations",
        "events",
        ["event_id"],
        ["[[[[id]]]]"],
        ondelete="CASCADE",
        use_alter=True,
    )
    op.create_foreign_key(
        op.f("fk_event_registrations_profile_id_profiles"),
        "event_registrations",
        "profiles",
        ["profile_id"],
        ["[[[[id]]]]"],
        ondelete="CASCADE",
        use_alter=True,
    )
    op.create_foreign_key(
        op.f("fk_events_organizer_id_organizers"),
        "events",
        "organizers",
        ["organizer_id"],
        ["[[[[id]]]]"],
        use_alter=True,
    )
    op.create_foreign_key(
        op.f("fk_events_category_id_categories"),
        "events",
        "categories",
        ["category_id"],
        ["[[[[id]]]]"],
        use_alter=True,
    )
    op.create_foreign_key(
        op.f("fk_events_location_id_locations"),
        "events",
        "locations",
        ["location_id"],
        ["[[[[id]]]]"],
        use_alter=True,
    )
    op.create_foreign_key(
        op.f("fk_organizers_user_id_users"),
        "organizers",
        "users",
        ["user_id"],
        ["[[[[id]]]]"],
        ondelete="CASCADE",
        use_alter=True,
    )
    op.create_foreign_key(
        op.f("fk_profiles_user_id_users"),
        "profiles",
        "users",
        ["user_id"],
        ["[[[[id]]]]"],
        ondelete="CASCADE",
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_profiles_user_id_users"), "profiles", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_organizers_user_id_users"), "organizers", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_events_location_id_locations"), "events", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_events_category_id_categories"), "events", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_events_organizer_id_organizers"), "events", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_event_registrations_profile_id_profiles"),
        "event_registrations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_event_registrations_event_id_events"),
        "event_registrations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_event_organizers_event_id_events"),
        "event_organizers",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_event_organizers_organizer_id_organizers"),
        "event_organizers",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
